### ISSUE TITLE
@everyone spam

### ISSUE THREAD

**Issue by aawadeus** [Walle-glitch/NIT-2.0#5]
När folk stavar fel på en roll med ./addrole så är @everyone en del av roles.json och det blir spammigt. Antingen kanske man ska ta bort @everyone ur roles.json eller börja roles_list från index 1 istället för 0, upp till dig!

Jag vet inte hur man gör pull requests så skriver detta i en issue, ska lära mig mer om att använda github. 

/Alex

**Comment by Walle-glitch** [comment]
Issue solved in version 2024-09-06.1
